name: copy_n_sync
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  google_fonts: ^3.0.1
  awesome_notifications: ^0.7.4+1

  # api
  dio: 4.0.6
  dartz: ^0.10.1
  socket_io_client: ^2.0.1
  flutter_isolate: ^2.0.4
  flutter_background: ^1.2.0
  window_manager: ^0.3.2

  # storage
  shared_preferences: ^2.1.0
  clipboard: ^0.1.3
  rich_clipboard: ^1.0.1

  # state management
  stacked: ^3.0.1
  stacked_services: ^0.9.9

  # Data Models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^2.3.3
  stacked_generator: ^1.0.0

  # data models
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
